# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

version: 0.4.1

sector:
  district_heating:
    potential: 0.3 #maximum fraction of urban demand which can be supplied by district heating
    #increase of today's district heating demand to potential maximum district heating share
    #progress = 0 means today's district heating share, progress=-1 means maximum fraction of urban demand is supplied by district heating
    progress: 1
    # 2020: 0.0
    # 2030: 0.3
    # 2040: 0.6
    # 2050: 1.0
    district_heating_loss: 0.15
  reduce_space_heat_exogenously: true # reduces space heat demand by a given factor (applied before losses in DH)
  # this can represent e.g. building renovation, building demolition, or if
  # the factor is negative: increasing floor area, increased thermal comfort, population growth
  reduce_space_heat_exogenously_factor: 0.29 # per unit reduction in space heat demand
  # the default factors are determined by the LTS scenario from http://tool.european-calculator.eu/app/buildings/building-types-area/?levers=1ddd4444421213bdbbbddd44444ffffff11f411111221111211l212221
  # 2020: 0.10  # this results in a space heat demand reduction of 10%
  # 2025: 0.09  # first heat demand increases compared to 2020 because of larger floor area per capita
  # 2030: 0.09
  # 2035: 0.11
  # 2040: 0.16
  # 2045: 0.21
  # 2050: 0.29

  tes: true
  tes_tau: # 180 day time constant for centralised, 3 day for decentralised
    decentral: 3
    central: 180
  boilers: true
  oil_boilers: false
  chp: true
  micro_chp: false
  solar_thermal: true
  heat_pump_sink_T: 55 #Celsius, based on DTU / large area radiators; used un build_cop_profiles.py
  time_dep_hp_cop: true #time dependent heat pump coefficient of performance
  solar_cf_correction: 0.788457 # = >>>1/1.2683
